global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "gpu"
    static_configs:
      - targets: ["dcgm_exporter:9400"]
